# Generated by Django 3.0.7 on 2020-06-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodCMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('INA', 'INACTIVE')], max_length=3, verbose_name='Active'),
        ),
        migrations.AlterUniqueTogether(
            name='nutridirectory',
            unique_together={('prod_id', 'nutri_info_id')},
        ),
    ]
